[package]
name = "rman-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = "22.10.26"
log = "0.4.17"
paste = "1.0.11"
thiserror = "1.0.38"
zstd = "0.12.1"

[features]
default = []
version_error = []
